nn:
  model: eSEN
  collate_fn: nn_collate_features
  model_args:
    nn_cutoff: 20.0
    max_num_elements: 67
    sphere_channels: 16
    lmax: 2
    mmax: 2
    edge_channels: 16
    distance_function: gaussian
    num_distance_basis: 10
    direct_forces: false
    num_layers: 2
    hidden_channels: 16
    norm_type: rms_norm_sh
    act_type: gate
    mlp_type: spectral
    use_envelope: true
    activation_checkpointing: true
prior:
  model: ForceField
  collate_fn: forcefield_collate_features
  model_args:
    nn_cutoff: 20.0
    return_forces: false
    has_bonded: true
    has_angles: true
    has_vdw: true
    has_wca: true
    has_coulomb: true
    has_dihedrals: true
    init_bonded_terms: true
    init_angle_terms: true
    init_dihedral_terms: true
    init_nonbonded_terms: true
    num_dihedral_basis: 10
    dielectric_constant: 1.0
    vdw_cutoff_distance: 20.0
train:
  lightning_model: UModel
  lightning_model_args:
    return_forces: false
    model_temperature: 300
    loss_type: force matching
    div_method: stein
    div_samples: 1
    div_epsilon: 0.0001
    vectorize_div: false
    l1_lambda: 1.0
    load_balance_lambda: 0.0
    layers_to_freeze:
    - prior.bonds_mean
    - prior.bonds_k
    - prior.angles_mean
    - prior.angles_k
    - prior.dihedral_a1
    - prior.dihedral_a2
    optimizer: Adam
    optimizer_args:
      nn_lr: 0.001
      prior_lr: 0.001
    lr_scheduler: ReduceLROnPlateau
    lr_scheduler_args:
      patience: 5
    monitor: val/TotalLoss
    sync_dist: true
    on_step: false
  resume_training_path: null
  trainer_args:
    accelerator: cuda
    devices: 4
    strategy: ddp_find_unused_parameters_true
    log_every_n_steps: 10000
    max_epochs: 40
    enable_progress_bar: false
    precision: 32-true
    accumulate_grad_batches: 1
  seed_args:
    seed: 42
    workers: true
global_args:
  use_nn: true
  use_prior: true
  load_model: ./lightning_logs/version_6/
dataset:
  model: NNDataset
  edge_args:
    only_cutoff_edges: true
    only_nonbonded: false
    update_edge_indices: false
  dtype: float32
  log_every_n_steps: 500
  data_in_memory: false
  batch_size: 8
  num_workers: 16
  dataset_split_args:
    train: 0.8
    val: 0.1
    test: 0.1
  individual_protein_datasets: null
  dataset_folder_name: /data2/scratch/group_scratch/cg/datasets/mdCATH_1000/
  adaption_dataset_folder_name: null
  train_dataset_fraction: 1.0
