[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cgp"
version = "0.0.1"
authors = [
  { name="Abigail Park", email="abpark@stanford.edu" },
  { name="Shriram Chennakesavalu", email="shriramc@stanford.edu" },
  { name="Grant Rotskoff", email="rotskoff@stanford.edu" },
]
description = "A package for coarse-grained model training and simulations"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "dask>=2023.5.0",
    "e3nn>=0.5.5",
    "einops>=0.8.1",
    "h5py>=3.11.0",
    "hydra-core>=1.3.2",
    "lightning>=2.3.3",
    "mdtraj>=1.10.0",
    "omegaconf>=2.3.0",
    "openmm>=8.1.1",
    "pandas>=2.2.3",
    "tensorboard",
    "torchtyping>=0.1.5",
    "PyYAML",
    "ruff>=0.15.1",
    "torch>=2.0.0",
    "cuequivariance==0.3.0",
    "cuequivariance-torch==0.3.0",
    "torch-geometric>=2.6.1",
]

[project.optional-dependencies]
cuda = [
    "openmm-cuda-12",
    "cuequivariance-ops-torch-cu12==0.5.1",
]

[tool.hatch.build.targets.sdist]
include = [
    "/cgp",
    "/cgp/cg",
    "/cgp/nn",
    "/cgp/omm",
    "/cgp/scripts",
    "/cgp/sim",
]

[project.urls]
Homepage = "https://github.com/rotskoff-group/transferable-cg"

[project.scripts]
u_train = "cgp.scripts.cg.train_u:main"
u_test = "cgp.scripts.cg.test_u:main"
make_u_dataset = "cgp.scripts.cg.make_u_dataset:main"
omm_sim = "cgp.scripts.omm.omm_sim:main"
cg_sim = "cgp.scripts.cg.cg_sim:main"
